// Auto-generated by train.py -- one real CWRU faulty bearing sample
// (post-FFT, post-standardization) so the QEMU demo prints a
// meaningful predicted class instead of using all-zero input.
pub static SAMPLE: [[[f32; 32]; 1]; 1] = [[[-6.21111_f32, -4.43132_f32, 11.1286_f32, 8.8726_f32, 0.359317_f32, -12.1278_f32, 16.281_f32, 25.9797_f32, 23.6029_f32, 22.4151_f32, 23.2413_f32, 9.0743_f32, 43.7307_f32, 75.3258_f32, 94.8033_f32, 108.988_f32, 51.327_f32, 102.764_f32, 116.412_f32, 127.203_f32, 83.2985_f32, 66.3675_f32, 59.6373_f32, 49.6515_f32, 46.6776_f32, 42.3648_f32, 17.5483_f32, 37.8905_f32, 23.6465_f32, 8.75346_f32, 1.23752_f32, 0.719665_f32]]];
pub const EXPECTED_CLASS: usize = 1;
