// Auto-generated by train.py -- one real CWRU faulty bearing sample
// (post-FFT, post-standardization) so the QEMU demo prints a
// meaningful predicted class instead of using all-zero input.
pub static SAMPLE: [[[f32; 32]; 1]; 1] = [[[-7.54833_f32, -2.28431_f32, 24.8696_f32, 17.384_f32, 2.35124_f32, -13.5943_f32, 13.8583_f32, 25.6707_f32, 29.3414_f32, 24.9658_f32, 17.6703_f32, -0.418187_f32, 49.7445_f32, 88.8938_f32, 127.146_f32, 145.778_f32, 77.9665_f32, 161.611_f32, 169.244_f32, 144.203_f32, 94.6796_f32, 75.5617_f32, 67.3857_f32, 56.3269_f32, 54.1994_f32, 59.2887_f32, 26.677_f32, 37.9171_f32, 31.886_f32, 20.7378_f32, 3.46576_f32, 1.06222_f32]]];
pub const EXPECTED_CLASS: usize = 1;
